/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kcd' at '17. 2. 20 오전 5:23' with Gradle 3.2.1
 *
 * @author kcd, @date 17. 2. 20 오전 5:23
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
